apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
spec:
  selector:
    app: flask-k8s
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s
spec:
  selector:
    matchLabels:
      app: flask-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-k8s
    spec:
      containers:
      - name: parcial3-sopes-flask
        image: dgo45921/flask_k8s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080